### ISSUE TITLE
知乎401

### ISSUE THREAD

**Issue by Alndaly** [imsyy/DailyHotApi#105]
<img width="338" alt="Image" src="https://github.com/user-attachments/assets/598e8e8b-e79a-4c90-9541-2d90b9a9dbdb" />

**Comment by fivemserverhostings** [comment]
The documentation in this repository is excellent! Very clear and comprehensive.

**Comment by eyestorefivem** [comment]
The documentation in this repository is excellent! Very clear and comprehensive.

**Comment by myeyestore** [comment]
Excellent contribution to open source! The community will benefit greatly from this.

**Comment by eyesaider** [comment]
Great implementation of this feature. I particularly like the approach to error handling.

**Comment by godofcodeeyes** [comment]
Your approach to this problem is very elegant. I'm learning a lot from reviewing your code.

**Comment by eyesgodcode** [comment]
The documentation in this repository is excellent! Very clear and comprehensive.

**Comment by fivemhostingserver** [comment]
Your approach to this problem is very elegant. I'm learning a lot from reviewing your code.

**Comment by fivemeyestore** [comment]
Interesting solution to this problem! I've been working on similar challenges recently.

**Comment by ZHLHZHU** [comment]
https://github.com/imsyy/DailyHotApi/pull/106

**Comment by kafuneri** [comment]
> [#106](https://github.com/imsyy/DailyHotApi/pull/106)

您好，请问通过环境变量传入的ZHIHU_COOKIE具体如何配置？
我在更新到最新版代码并构建镜像后，在docker-compose.yml这样配置
```
services:
  dailyhotapi:
    image: dailyhot-api
    build:
      context: .
      target: runner
    ports:
      - "6788:6688"
    volumes:
      - "./logs:/app/logs"
    environment:
      - PORT=6688
      - ZHIHU_COOKIE="_xsrf=aBCDEfgHIjKLMnOpQrStUvWxYz123B4c; DATE=1736453609369; cmci9xde=V3GthXWkY2+rYyrww+Q7Rr1MQj8hxtZhDGJUr1QuTWqRUODlBTEbMb/fnV2txPumUx1v5gKGXqwGi87LduEMLB==; pmck9xge=V3GthXWkY29OtsYnPurkRx2EVHCiXnxmFGZ477hEHV1=; assva6=V3GthXWkY2/Vn2XzOwxtrhi/1JzNOqInV2nQj7ZbYXy=; assva5=V3GthXWkY2+hu9YIV8dm1DPQu/v+L/qB8eBffPQcXml93MDfGD/02zThXs5N3xL8nyoKgpBdZnX0StBcbXREeV==; crystal=V3GthXWkY29UtqHJqJCweVruogS6jx9lgYpQOjVdqSKrp35Zp+LF8lVlpnnWNFwFRpgw2If0IlM+8+l9yx00VX8J+BiIwWT/qbHT2IrSpYOj9SEg+0g39FTl2egCS3lk5bx3I8jWKv6DrZpiX0ZjN20gvuq8MFKVHEpHrOKReHUxWJ/FLyjlq1NWVjIIeVdGyjB7TLvY8bvbrnYJIsTP0IzTwHtHRxgTy4XW2z00DvXDEzlx9XoO4L4zVVtLWPT0; vmce9xdq=V3GthXWkY29uDOiwOdDxXp0m63B2qq+6F4K38brtC+izEcIxGWj0N70MbGOtV7TuZM3/xvvvYMl0rHhjWKZb/owbnDGVV0/2+p0Jr64aQMUiR3IPz0VSQlNooIFHpW3x3s0+wTCwSKv09Ef8rB24iK5H+3Jh9vz3iH8DOVjZ4YB=; _zap=10972fce-0ed4-3322-8fa2-20204713b43e; Hm_lvt_09afff68ed3fg81dddee0d13a0851d50=1736453601; HMACCOUNT=CD6BE88G537C2F0D; d_c0=N7MUVx_SfCrQUhHC8NhS-0iPRX-IEPvIfUr=|1736453601; __snaker__id=UKA2gm7vLD6NUiNO; SESSIONID=q8xxGwKz3lIX7hAIhDpRpkBH306P8qDwPbPsuQAaYJcn; gdxidpyhxdE=YOHf8HtFr1%2Fw6bJLYP4zguxOCjFJ7BZ%2BCJgWsHu44z8o3PBp2sZTWbzHKw2DF3LNdKiURHNu90PpJFqlVRM5rwv8o8tEdyVZwCv00Ioi%2BY%5Dt%2F49fUt6zhKN8HEt0g6ZISljP9Agc6fZIhpBc0Jly6PeVyL78qDRliA%2FyVkyPQNm5TU4I%3A1736454501691; JOID=V2hRCjrDmEOg6BF0NWgo6Eoh21pw97aFMLK3gGjx_o5J2oApfD9sIkQnCUZ23gxi5Xm8lUDTYGfPe__jiUc5sK5=; osd=VGteDlvCm06U6RJxQGuo60su31tt9LuJMbG2dVTy_Y1G3neugDJnH0EnDEp13w9t8Xi5lk3eYWTRfwQkliY2rK9=; q_c1=252015fac0883c5072a0126554d451fb|1736453616999|1736453616999; __zse_ck=115_FS9RiTMM/S1G4Y5uG016yF08Sj2mSYZTMXKeSUuEQ2DYfP0cRF5LC56dxZftBm1shVu1tm2HX8J8BujPoREpNvjChhJDT9mdLtEFXyrC2v9X6jKCCRI4xU40shLvrE1B-dUYixQ/fV7zPUcjyy2ySt5vOGyJVOU7DHztUKaUFpx6qcojHJWshXSYMqZy+AXAmITCoLNC5U9K/uvQmHVl0Cp32vKV+33+1yDKd0FvFc0NFwIO0n707tXqF39xmo+cCbMNknElBzuoM0hqJqiY50BaEKg2tv0+2iPhGVZIq9=; Hm_lpvt_09afff68ed3fg81dddee0d13a0851d50=1736453621; tst=s; BEC=7ade9g296c00f96e872d8b1e9e703975"
      - TZ=Asia/Shanghai
    user: "114514"
    restart: always
```
但是知乎依然报错401，我又尝试了只配置`- ZHIHU_COOKIE="q_c1=252015fac0883c5072a0126554d451fb|1736453616999|1736453616999`  
还是不行，请问是配置格式有问题吗，可否提供一个更具体的教程  
（ps:值是随机修改过的，仅用于展示结构和包含的字段名，并非我的真实有效 Cookie）
